steps:
  build-and-push:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: "${CI_REPO_OWNER}/${CI_REPO_NAME}"
      tags: "feature-${CI_COMMIT_BRANCH##feature/}"
    secrets: [docker_username, docker_password]
when:
  event: push
  branch: feature/*
